controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# 名前:
#     path: パスの指定
#     controller: コントローラ::アクション
# hello:
#     path: /hello
#     controller: App\Controller\HelloController::index